NSE_STOCKS: dict[str, str] = {
    # --- Nifty 50 / Large Cap ---
    "RELIANCE":    "Reliance Industries",
    "TCS":         "Tata Consultancy Services",
    "HDFCBANK":    "HDFC Bank",
    "INFY":        "Infosys",
    "ICICIBANK":   "ICICI Bank",
    "HINDUNILVR":  "Hindustan Unilever",
    "SBIN":        "State Bank of India",
    "BHARTIARTL":  "Bharti Airtel",
    "ITC":         "ITC Limited",
    "KOTAKBANK":   "Kotak Mahindra Bank",
    "LT":          "Larsen & Toubro",
    "AXISBANK":    "Axis Bank",
    "ASIANPAINT":  "Asian Paints",
    "BAJFINANCE":  "Bajaj Finance",
    "WIPRO":       "Wipro",
    "MARUTI":      "Maruti Suzuki",
    "TITAN":       "Titan Company",
    "ULTRACEMCO":  "UltraTech Cement",
    "SUNPHARMA":   "Sun Pharmaceutical",
    "NESTLEIND":   "Nestle India",
    "TATAMOTORS":  "Tata Motors",
    "POWERGRID":   "Power Grid Corporation",
    "NTPC":        "NTPC Limited",
    "ONGC":        "Oil and Natural Gas Corporation",
    "COALINDIA":   "Coal India",
    "TATASTEEL":   "Tata Steel",
    "ADANIENT":    "Adani Enterprises",
    "ADANIPORTS":  "Adani Ports",
    "JSWSTEEL":    "JSW Steel",
    "HCLTECH":     "HCL Technologies",
    "TECHM":       "Tech Mahindra",
    "DRREDDY":     "Dr. Reddy's Laboratories",
    "CIPLA":       "Cipla",
    "DIVISLAB":    "Divi's Laboratories",
    "APOLLOHOSP":  "Apollo Hospitals",
    "BAJAJFINSV":  "Bajaj Finserv",
    "BPCL":        "Bharat Petroleum",
    "HEROMOTOCO":  "Hero MotoCorp",
    "EICHERMOT":   "Eicher Motors",
    "INDUSINDBK":  "IndusInd Bank",
    "M&M":         "Mahindra & Mahindra",
    "HDFCLIFE":    "HDFC Life Insurance",
    "SBILIFE":     "SBI Life Insurance",
    "GRASIM":      "Grasim Industries",
    "HINDALCO":    "Hindalco Industries",
    "TATACONSUM":  "Tata Consumer Products",
    "UPL":         "UPL Limited",
    "BRITANNIA":   "Britannia Industries",
    "SHREECEM":    "Shree Cement",
    "PIDILITIND":  "Pidilite Industries",
    # --- IT / Technology ---
    "LTIM":        "LTIMindtree",
    "MPHASIS":     "Mphasis",
    "PERSISTENT":  "Persistent Systems",
    "COFORGE":     "Coforge",
    "TATAELXSI":   "Tata Elxsi",
    "KPITTECH":    "KPIT Technologies",
    "ZENSARTECH":  "Zensar Technologies",
    "MASTEK":      "Mastek",
    "TANLA":       "Tanla Platforms",
    "RATEGAIN":    "RateGain Travel Technologies",
    "NAUKRI":      "Info Edge (Naukri)",
    "JUSTDIAL":    "Just Dial",
    "IRCTC":       "Indian Railway Catering & Tourism",
    # --- Banking & Finance ---
    "BANKBARODA":  "Bank of Baroda",
    "CANARABANK":  "Canara Bank",
    "PNB":         "Punjab National Bank",
    "UNIONBANK":   "Union Bank of India",
    "INDIANB":     "Indian Bank",
    "FEDERALBANK": "Federal Bank",
    "IDFCFIRSTB":  "IDFC First Bank",
    "AUBANK":      "AU Small Finance Bank",
    "BANDHANBNK":  "Bandhan Bank",
    "RBLBANK":     "RBL Bank",
    "YESBANK":     "Yes Bank",
    "LICHSGFIN":   "LIC Housing Finance",
    "CHOLAFIN":    "Cholamandalam Investment",
    "M&MFIN":      "Mahindra & Mahindra Financial Services",
    "MANAPPURAM":  "Manappuram Finance",
    "MUTHOOTFIN":  "Muthoot Finance",
    "PIRAMALENT":  "Piramal Enterprises",
    "JIOFIN":      "Jio Financial Services",
    "HDFCAMC":     "HDFC AMC",
    "NIPPONLIFE":  "Nippon India AMC",
    "ICICIGI":     "ICICI Lombard General Insurance",
    "ICICIPRULI":  "ICICI Prudential Life Insurance",
    "STARHEALTH":  "Star Health Insurance",
    "GICRE":       "General Insurance Corporation",
    "NIACL":       "New India Assurance",
    # --- Pharma & Healthcare ---
    "LUPIN":       "Lupin",
    "TORNTPHARM":  "Torrent Pharmaceuticals",
    "BIOCON":      "Biocon",
    "GLENMARK":    "Glenmark Pharmaceuticals",
    "IPCALAB":     "IPCA Laboratories",
    "AUROPHARMA":  "Aurobindo Pharma",
    "GRANULES":    "Granules India",
    "LAURUSLABS":  "Laurus Labs",
    "ALKEM":       "Alkem Laboratories",
    "ABBOTINDIA":  "Abbott India",
    "PFIZER":      "Pfizer India",
    "GLAXO":       "GSK Pharmaceuticals",
    "FORTIS":      "Fortis Healthcare",
    "MAXHEALTH":   "Max Healthcare",
    "NARAYANA":    "Narayana Hrudayalaya",
    "RAINBOW":     "Rainbow Children's Medicare",
    # --- FMCG & Consumer ---
    "DABUR":       "Dabur India",
    "MARICO":      "Marico",
    "GODREJCP":    "Godrej Consumer Products",
    "COLPAL":      "Colgate-Palmolive India",
    "EMAMILTD":    "Emami",
    "PGHH":        "Procter & Gamble Hygiene & Health",
    "VARBEV":      "Varun Beverages",
    "RADICO":      "Radico Khaitan",
    "UNITDSPR":    "United Spirits",
    "JUBLFOOD":    "Jubilant FoodWorks",
    "DEVYANI":     "Devyani International",
    "SAPPHIRE":    "Sapphire Foods India",
    "RELAXO":      "Relaxo Footwears",
    "BATA":        "Bata India",
    "METROBRAND":  "Metro Brands",
    "CAMPUS":      "Campus Activewear",
    "PAGEIND":     "Page Industries",
    "VBL":         "Varun Beverages",
    # --- Automobiles ---
    "BAJAJ-AUTO":  "Bajaj Auto",
    "TVSMOTOR":    "TVS Motor Company",
    "ASHOKLEY":    "Ashok Leyland",
    "MOTHERSON":   "Samvardhana Motherson",
    "BOSCH":       "Bosch India",
    "APOLLOTYRE":  "Apollo Tyres",
    "CEATLTD":     "CEAT",
    "BALKRISIND":  "Balkrishna Industries",
    "SCHAEFFLER":  "Schaeffler India",
    "TIINDIA":     "Tube Investments of India",
    # --- Energy & Power ---
    "TATAPOWER":   "Tata Power",
    "TORNTPOWER":  "Torrent Power",
    "JSWENERGY":   "JSW Energy",
    "CESC":        "CESC",
    "ADANIGREEN":  "Adani Green Energy",
    "ADANIPOWER":  "Adani Power",
    "NHPC":        "NHPC",
    "SJVN":        "SJVN",
    "PFC":         "Power Finance Corporation",
    "RECLTD":      "REC Limited",
    # --- Infrastructure & Real Estate ---
    "DLF":         "DLF",
    "GODREJPROP":  "Godrej Properties",
    "OBEROIRLTY":  "Oberoi Realty",
    "PRESTIGE":    "Prestige Estates Projects",
    "BRIGADE":     "Brigade Enterprises",
    "SOBHA":       "Sobha",
    "PHOENIXLTD":  "Phoenix Mills",
    "MAHLIFE":     "Mahindra Lifespace Developers",
    "SUNCLAYLTD":  "Sunclay Limited",
    "IRFC":        "Indian Railway Finance Corporation",
    "RVNL":        "Rail Vikas Nigam",
    "HUDCO":       "Housing & Urban Dev. Corp.",
    "IRB":         "IRB Infrastructure",
    "GMR":         "GMR Airports Infrastructure",
    "CONCOR":      "Container Corporation of India",
    "APLAPOLLO":   "APL Apollo Tubes",
    # --- Metals & Mining ---
    "VEDL":        "Vedanta",
    "NMDC":        "NMDC",
    "NATIONALUM":  "National Aluminium Company",
    "JINDALSTEL":  "Jindal Steel & Power",
    "JSL":         "Jindal Stainless",
    "MOIL":        "MOIL",
    "RATNAMANI":   "Ratnamani Metals & Tubes",
    # --- Cement ---
    "JKCEMENT":    "JK Cement",
    "RAMCOCEM":    "Ramco Cements",
    "INDIACEM":    "India Cements",
    "HEIDELBERG":  "HeidelbergCement India",
    "DALMIACEM":   "Dalmia Bharat",
    "JKLAKMISHMI": "JK Lakshmi Cement",
    # --- Chemicals ---
    "SRF":         "SRF",
    "DEEPAKNTR":   "Deepak Nitrite",
    "AARTIIND":    "Aarti Industries",
    "NOCIL":       "NOCIL",
    "VINATIORGA":  "Vinati Organics",
    "FINEORG":     "Fine Organic Industries",
    "TATACHEM":    "Tata Chemicals",
    "GNFC":        "Gujarat Narmada Valley Fertilizers",
    "CHAMBLFERT":  "Chambal Fertilizers",
    "COROMANDEL":  "Coromandel International",
    # --- Telecom & Media ---
    "IDEA":        "Vodafone Idea",
    "INDIGO":      "InterGlobe Aviation (IndiGo)",
    "SUNTV":       "Sun TV Network",
    "ZEEL":        "Zee Entertainment",
    "NETWORK18":   "Network18 Media",
    # --- Conglomerates & Others ---
    "GODREJIND":   "Godrej Industries",
    "TATACOMM":    "Tata Communications",
    "MCDOWELL-N":  "United Spirits",
    "RAYMOND":     "Raymond",
    "TRIDENT":     "Trident",
    "WELCORP":     "Welspun Corp",
    "HAVELLS":     "Havells India",
    "VOLTAS":      "Voltas",
    "BLUESTARCO":  "Blue Star",
    "WHIRLPOOL":   "Whirlpool of India",
    "CROMPTON":    "Crompton Greaves Consumer",
    "DIXON":       "Dixon Technologies",
    "AMBER":       "Amber Enterprises India",
    "KAYNES":      "Kaynes Technology India",
    "SYRMA":       "Syrma SGS Technology",
    "POLICYBZR":   "PB Fintech (PolicyBazaar)",
    "PAYTM":       "One 97 Communications (Paytm)",
    "ZOMATO":      "Zomato",
    "NYKAA":       "FSN E-Commerce (Nykaa)",
    "CARTRADE":    "CarTrade Tech",
    "DELHIVERY":   "Delhivery",
    "MAPMYINDIA":  "CE Info Systems (MapMyIndia)",
    "ROUTE":       "Route Mobile",
    "HAPPSTMNDS":  "Happiest Minds Technologies",
    "NEWGEN":      "Newgen Software",
    "INFIBEAM":    "Infibeam Avenues",
}

BSE_STOCKS: dict[str, str] = {
    # BSE-listed companies with distinct BSE ticker conventions
    "SENSEX":      "BSE SENSEX Index",
    "500002":      "ABB India",
    "TATAINVEST":  "Tata Investment Corporation",
    "BOMBSHELL":   "Bombay Dyeing",
    "CENTURYTEX":  "Century Textiles & Industries",
    "CENTURYPLY":  "Century Plyboards",
    "MAHSCOOTER":  "Maharashtra Scooters",
    "GUJALKALI":   "Gujarat Alkalies & Chemicals",
    "SWANENERGY":  "Swan Energy",
    "WALCHANNAG":  "Walchandnagar Industries",
    "ESABINDIA":   "Esab India",
    "TINPLATE":    "Tinplate Company of India",
    "TCNSBRANDS":  "TCNS Clothing",
    "MAFANG":      "Mafatlal Industries",
    "PCBL":        "PCBL (Philips Carbon Black)",
    "REDINGTON":   "Redington India",
    "WELSPUNIND":  "Welspun India",
    "JYOTHYLAB":   "Jyothy Labs",
    "SPANDANA":    "Spandana Sphoorty Financial",
    "FIVESTAR":    "Five-Star Business Finance",
}

SECTOR_MAP: dict[str, str] = {
    "RELIANCE": "Energy & Petrochemicals", "TCS": "Information Technology",
    "HDFCBANK": "Banking & Finance", "INFY": "Information Technology",
    "ICICIBANK": "Banking & Finance", "HINDUNILVR": "FMCG",
    "SBIN": "Banking & Finance", "BHARTIARTL": "Telecom",
    "ITC": "FMCG", "KOTAKBANK": "Banking & Finance",
    "LT": "Infrastructure", "AXISBANK": "Banking & Finance",
    "ASIANPAINT": "Chemicals & Paints", "BAJFINANCE": "Banking & Finance",
    "WIPRO": "Information Technology", "MARUTI": "Automobile",
    "TITAN": "Consumer Goods", "ULTRACEMCO": "Cement",
    "SUNPHARMA": "Pharmaceuticals", "NESTLEIND": "FMCG",
    "TATAMOTORS": "Automobile", "POWERGRID": "Power & Energy",
    "NTPC": "Power & Energy", "ONGC": "Oil & Gas",
    "COALINDIA": "Mining", "TATASTEEL": "Metals & Steel",
    "ADANIENT": "Conglomerate", "ADANIPORTS": "Infrastructure",
    "JSWSTEEL": "Metals & Steel", "HCLTECH": "Information Technology",
    "TECHM": "Information Technology", "DRREDDY": "Pharmaceuticals",
    "CIPLA": "Pharmaceuticals", "DIVISLAB": "Pharmaceuticals",
    "APOLLOHOSP": "Healthcare", "BAJAJFINSV": "Banking & Finance",
    "BPCL": "Oil & Gas", "HEROMOTOCO": "Automobile",
    "EICHERMOT": "Automobile", "INDUSINDBK": "Banking & Finance",
    "M&M": "Automobile", "HDFCLIFE": "Insurance",
    "SBILIFE": "Insurance", "GRASIM": "Cement",
    "HINDALCO": "Metals & Steel", "TATACONSUM": "FMCG",
    "UPL": "Agrochemicals", "BRITANNIA": "FMCG",
    "SHREECEM": "Cement", "PIDILITIND": "Chemicals & Paints",
    # IT
    "LTIM": "Information Technology", "MPHASIS": "Information Technology",
    "PERSISTENT": "Information Technology", "COFORGE": "Information Technology",
    "TATAELXSI": "Information Technology", "KPITTECH": "Information Technology",
    "ZENSARTECH": "Information Technology", "MASTEK": "Information Technology",
    "TANLA": "Information Technology", "RATEGAIN": "Information Technology",
    "NAUKRI": "Information Technology", "JUSTDIAL": "Information Technology",
    "IRCTC": "Infrastructure",
    # Banking & Finance
    "BANKBARODA": "Banking & Finance", "CANARABANK": "Banking & Finance",
    "PNB": "Banking & Finance", "UNIONBANK": "Banking & Finance",
    "INDIANB": "Banking & Finance", "FEDERALBANK": "Banking & Finance",
    "IDFCFIRSTB": "Banking & Finance", "AUBANK": "Banking & Finance",
    "BANDHANBNK": "Banking & Finance", "RBLBANK": "Banking & Finance",
    "YESBANK": "Banking & Finance", "LICHSGFIN": "Banking & Finance",
    "CHOLAFIN": "Banking & Finance", "M&MFIN": "Banking & Finance",
    "MANAPPURAM": "Banking & Finance", "MUTHOOTFIN": "Banking & Finance",
    "PIRAMALENT": "Banking & Finance", "JIOFIN": "Banking & Finance",
    "HDFCAMC": "Banking & Finance", "NIPPONLIFE": "Banking & Finance",
    "ICICIGI": "Insurance", "ICICIPRULI": "Insurance",
    "STARHEALTH": "Insurance", "GICRE": "Insurance", "NIACL": "Insurance",
    # Pharma
    "LUPIN": "Pharmaceuticals", "TORNTPHARM": "Pharmaceuticals",
    "BIOCON": "Pharmaceuticals", "GLENMARK": "Pharmaceuticals",
    "IPCALAB": "Pharmaceuticals", "AUROPHARMA": "Pharmaceuticals",
    "GRANULES": "Pharmaceuticals", "LAURUSLABS": "Pharmaceuticals",
    "ALKEM": "Pharmaceuticals", "ABBOTINDIA": "Pharmaceuticals",
    "PFIZER": "Pharmaceuticals", "GLAXO": "Pharmaceuticals",
    "FORTIS": "Healthcare", "MAXHEALTH": "Healthcare",
    "NARAYANA": "Healthcare", "RAINBOW": "Healthcare",
    # FMCG & Consumer
    "DABUR": "FMCG", "MARICO": "FMCG", "GODREJCP": "FMCG",
    "COLPAL": "FMCG", "EMAMILTD": "FMCG", "PGHH": "FMCG",
    "VARBEV": "FMCG", "VBL": "FMCG", "RADICO": "FMCG",
    "UNITDSPR": "FMCG", "JUBLFOOD": "Consumer Goods",
    "DEVYANI": "Consumer Goods", "SAPPHIRE": "Consumer Goods",
    "RELAXO": "Consumer Goods", "BATA": "Consumer Goods",
    "METROBRAND": "Consumer Goods", "CAMPUS": "Consumer Goods",
    "PAGEIND": "Consumer Goods",
    # Auto
    "BAJAJ-AUTO": "Automobile", "TVSMOTOR": "Automobile",
    "ASHOKLEY": "Automobile", "MOTHERSON": "Automobile",
    "BOSCH": "Automobile", "APOLLOTYRE": "Automobile",
    "CEATLTD": "Automobile", "BALKRISIND": "Automobile",
    "SCHAEFFLER": "Automobile", "TIINDIA": "Automobile",
    # Energy & Power
    "TATAPOWER": "Power & Energy", "TORNTPOWER": "Power & Energy",
    "JSWENERGY": "Power & Energy", "CESC": "Power & Energy",
    "ADANIGREEN": "Power & Energy", "ADANIPOWER": "Power & Energy",
    "NHPC": "Power & Energy", "SJVN": "Power & Energy",
    "PFC": "Banking & Finance", "RECLTD": "Banking & Finance",
    # Real Estate & Infra
    "DLF": "Real Estate", "GODREJPROP": "Real Estate",
    "OBEROIRLTY": "Real Estate", "PRESTIGE": "Real Estate",
    "BRIGADE": "Real Estate", "SOBHA": "Real Estate",
    "PHOENIXLTD": "Real Estate", "MAHLIFE": "Real Estate",
    "IRFC": "Infrastructure", "RVNL": "Infrastructure",
    "HUDCO": "Infrastructure", "IRB": "Infrastructure",
    "GMR": "Infrastructure", "CONCOR": "Infrastructure",
    "APLAPOLLO": "Metals & Steel",
    # Metals & Mining
    "VEDL": "Metals & Steel", "NMDC": "Mining",
    "NATIONALUM": "Metals & Steel", "JINDALSTEL": "Metals & Steel",
    "JSL": "Metals & Steel", "MOIL": "Mining",
    "RATNAMANI": "Metals & Steel",
    # Cement
    "JKCEMENT": "Cement", "RAMCOCEM": "Cement",
    "INDIACEM": "Cement", "HEIDELBERG": "Cement",
    "DALMIACEM": "Cement", "JKLAKMISHMI": "Cement",
    # Chemicals
    "SRF": "Chemicals", "DEEPAKNTR": "Chemicals",
    "AARTIIND": "Chemicals", "NOCIL": "Chemicals",
    "VINATIORGA": "Chemicals", "FINEORG": "Chemicals",
    "TATACHEM": "Chemicals", "GNFC": "Chemicals",
    "CHAMBLFERT": "Agrochemicals", "COROMANDEL": "Agrochemicals",
    # Telecom & Media & Aviation
    "IDEA": "Telecom", "INDIGO": "Aviation",
    "SUNTV": "Media", "ZEEL": "Media", "NETWORK18": "Media",
    # Others
    "GODREJIND": "Conglomerate", "TATACOMM": "Information Technology",
    "RAYMOND": "Textiles", "TRIDENT": "Textiles",
    "WELCORP": "Metals & Steel", "HAVELLS": "Consumer Goods",
    "VOLTAS": "Consumer Goods", "BLUESTARCO": "Consumer Goods",
    "WHIRLPOOL": "Consumer Goods", "CROMPTON": "Consumer Goods",
    "DIXON": "Electronics", "AMBER": "Electronics",
    "KAYNES": "Electronics", "SYRMA": "Electronics",
    "POLICYBZR": "Fintech", "PAYTM": "Fintech",
    "ZOMATO": "Consumer Tech", "NYKAA": "Consumer Tech",
    "CARTRADE": "Consumer Tech", "DELHIVERY": "Logistics",
    "MAPMYINDIA": "Information Technology", "ROUTE": "Information Technology",
    "HAPPSTMNDS": "Information Technology", "NEWGEN": "Information Technology",
    "INFIBEAM": "Fintech", "MCDOWELL-N": "FMCG",
    # BSE stocks
    "TATAINVEST": "Banking & Finance", "CENTURYTEX": "Textiles",
    "CENTURYPLY": "Consumer Goods", "WELSPUNIND": "Textiles",
    "JYOTHYLAB": "FMCG", "PCBL": "Chemicals",
    "REDINGTON": "Information Technology", "SPANDANA": "Banking & Finance",
    "FIVESTAR": "Banking & Finance", "TCNSBRANDS": "Consumer Goods",
}

COMPETITORS: dict[str, list[str]] = {
    "TCS": ["INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM"],
    "INFY": ["TCS", "WIPRO", "HCLTECH", "TECHM", "LTIM"],
    "WIPRO": ["TCS", "INFY", "HCLTECH", "TECHM", "LTIM"],
    "HCLTECH": ["TCS", "INFY", "WIPRO", "TECHM", "LTIM"],
    "TECHM": ["TCS", "INFY", "WIPRO", "HCLTECH"],
    "LTIM": ["TCS", "INFY", "WIPRO", "HCLTECH"],
    "MPHASIS": ["TCS", "INFY", "PERSISTENT", "COFORGE"],
    "PERSISTENT": ["MPHASIS", "COFORGE", "LTIM"],
    "COFORGE": ["PERSISTENT", "MPHASIS", "LTIM"],
    "HDFCBANK": ["ICICIBANK", "KOTAKBANK", "AXISBANK", "SBIN", "INDUSINDBK"],
    "ICICIBANK": ["HDFCBANK", "KOTAKBANK", "AXISBANK", "SBIN"],
    "SBIN": ["HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK", "BANKBARODA"],
    "AXISBANK": ["HDFCBANK", "ICICIBANK", "KOTAKBANK", "SBIN"],
    "KOTAKBANK": ["HDFCBANK", "ICICIBANK", "AXISBANK", "SBIN"],
    "BANKBARODA": ["SBIN", "PNB", "CANARABANK", "UNIONBANK"],
    "PNB": ["SBIN", "BANKBARODA", "CANARABANK"],
    "RELIANCE": ["ONGC", "BPCL", "TATACHEM"],
    "ONGC": ["RELIANCE", "BPCL"],
    "BPCL": ["RELIANCE", "ONGC"],
    "MARUTI": ["TATAMOTORS", "M&M", "HEROMOTOCO", "EICHERMOT", "TVSMOTOR"],
    "TATAMOTORS": ["MARUTI", "M&M", "HEROMOTOCO", "EICHERMOT"],
    "M&M": ["MARUTI", "TATAMOTORS", "HEROMOTOCO"],
    "BAJAJ-AUTO": ["HEROMOTOCO", "TVSMOTOR", "EICHERMOT"],
    "HEROMOTOCO": ["BAJAJ-AUTO", "TVSMOTOR", "M&M"],
    "TVSMOTOR": ["BAJAJ-AUTO", "HEROMOTOCO", "EICHERMOT"],
    "SUNPHARMA": ["DRREDDY", "CIPLA", "DIVISLAB", "LUPIN"],
    "DRREDDY": ["SUNPHARMA", "CIPLA", "DIVISLAB", "LUPIN"],
    "CIPLA": ["SUNPHARMA", "DRREDDY", "DIVISLAB", "LUPIN"],
    "LUPIN": ["SUNPHARMA", "DRREDDY", "CIPLA", "AUROPHARMA"],
    "HINDUNILVR": ["ITC", "DABUR", "MARICO", "GODREJCP"],
    "ITC": ["HINDUNILVR", "DABUR", "MARICO"],
    "DABUR": ["HINDUNILVR", "MARICO", "GODREJCP", "EMAMILTD"],
    "MARICO": ["HINDUNILVR", "DABUR", "GODREJCP"],
    "BAJFINANCE": ["CHOLAFIN", "MUTHOOTFIN", "MANAPPURAM", "M&MFIN"],
    "CHOLAFIN": ["BAJFINANCE", "M&MFIN", "MANAPPURAM"],
    "MUTHOOTFIN": ["MANAPPURAM", "BAJFINANCE"],
    "ADANIENT": ["RELIANCE", "TATASTEEL"],
    "ADANIPORTS": ["CONCOR", "GMR"],
    "ADANIGREEN": ["TATAPOWER", "JSWENERGY", "TORNTPOWER"],
    "TATAPOWER": ["ADANIGREEN", "JSWENERGY", "NTPC"],
    "DLF": ["GODREJPROP", "OBEROIRLTY", "PRESTIGE"],
    "GODREJPROP": ["DLF", "OBEROIRLTY", "PRESTIGE"],
    "ZOMATO": ["JUBLFOOD", "DEVYANI", "SAPPHIRE"],
}
