export interface StockInfo {
  ticker: string
  name: string
  sector: string
}

export const NSE_STOCKS: StockInfo[] = [
  // Nifty 50 / Large Cap
  { ticker: "RELIANCE",    name: "Reliance Industries",                       sector: "Energy & Petrochemicals" },
  { ticker: "TCS",         name: "Tata Consultancy Services",                 sector: "Information Technology" },
  { ticker: "HDFCBANK",    name: "HDFC Bank",                                 sector: "Banking & Finance" },
  { ticker: "INFY",        name: "Infosys",                                   sector: "Information Technology" },
  { ticker: "ICICIBANK",   name: "ICICI Bank",                                sector: "Banking & Finance" },
  { ticker: "HINDUNILVR",  name: "Hindustan Unilever",                        sector: "FMCG" },
  { ticker: "SBIN",        name: "State Bank of India",                       sector: "Banking & Finance" },
  { ticker: "BHARTIARTL",  name: "Bharti Airtel",                             sector: "Telecom" },
  { ticker: "ITC",         name: "ITC Limited",                               sector: "FMCG" },
  { ticker: "KOTAKBANK",   name: "Kotak Mahindra Bank",                       sector: "Banking & Finance" },
  { ticker: "LT",          name: "Larsen & Toubro",                           sector: "Infrastructure" },
  { ticker: "AXISBANK",    name: "Axis Bank",                                 sector: "Banking & Finance" },
  { ticker: "ASIANPAINT",  name: "Asian Paints",                              sector: "Chemicals & Paints" },
  { ticker: "BAJFINANCE",  name: "Bajaj Finance",                             sector: "Banking & Finance" },
  { ticker: "WIPRO",       name: "Wipro",                                     sector: "Information Technology" },
  { ticker: "MARUTI",      name: "Maruti Suzuki",                             sector: "Automobile" },
  { ticker: "TITAN",       name: "Titan Company",                             sector: "Consumer Goods" },
  { ticker: "ULTRACEMCO",  name: "UltraTech Cement",                          sector: "Cement" },
  { ticker: "SUNPHARMA",   name: "Sun Pharmaceutical",                        sector: "Pharmaceuticals" },
  { ticker: "NESTLEIND",   name: "Nestle India",                              sector: "FMCG" },
  { ticker: "TATAMOTORS",  name: "Tata Motors",                               sector: "Automobile" },
  { ticker: "POWERGRID",   name: "Power Grid Corporation",                    sector: "Power & Energy" },
  { ticker: "NTPC",        name: "NTPC Limited",                              sector: "Power & Energy" },
  { ticker: "ONGC",        name: "Oil and Natural Gas Corporation",           sector: "Oil & Gas" },
  { ticker: "COALINDIA",   name: "Coal India",                                sector: "Mining" },
  { ticker: "TATASTEEL",   name: "Tata Steel",                                sector: "Metals & Steel" },
  { ticker: "ADANIENT",    name: "Adani Enterprises",                         sector: "Conglomerate" },
  { ticker: "ADANIPORTS",  name: "Adani Ports",                               sector: "Infrastructure" },
  { ticker: "JSWSTEEL",    name: "JSW Steel",                                 sector: "Metals & Steel" },
  { ticker: "HCLTECH",     name: "HCL Technologies",                          sector: "Information Technology" },
  { ticker: "TECHM",       name: "Tech Mahindra",                             sector: "Information Technology" },
  { ticker: "DRREDDY",     name: "Dr. Reddy's Laboratories",                  sector: "Pharmaceuticals" },
  { ticker: "CIPLA",       name: "Cipla",                                     sector: "Pharmaceuticals" },
  { ticker: "DIVISLAB",    name: "Divi's Laboratories",                       sector: "Pharmaceuticals" },
  { ticker: "APOLLOHOSP",  name: "Apollo Hospitals",                          sector: "Healthcare" },
  { ticker: "BAJAJFINSV",  name: "Bajaj Finserv",                             sector: "Banking & Finance" },
  { ticker: "BPCL",        name: "Bharat Petroleum",                          sector: "Oil & Gas" },
  { ticker: "HEROMOTOCO",  name: "Hero MotoCorp",                             sector: "Automobile" },
  { ticker: "EICHERMOT",   name: "Eicher Motors",                             sector: "Automobile" },
  { ticker: "INDUSINDBK",  name: "IndusInd Bank",                             sector: "Banking & Finance" },
  { ticker: "M&M",         name: "Mahindra & Mahindra",                       sector: "Automobile" },
  { ticker: "HDFCLIFE",    name: "HDFC Life Insurance",                       sector: "Insurance" },
  { ticker: "SBILIFE",     name: "SBI Life Insurance",                        sector: "Insurance" },
  { ticker: "GRASIM",      name: "Grasim Industries",                         sector: "Cement" },
  { ticker: "HINDALCO",    name: "Hindalco Industries",                       sector: "Metals & Steel" },
  { ticker: "TATACONSUM",  name: "Tata Consumer Products",                    sector: "FMCG" },
  { ticker: "UPL",         name: "UPL Limited",                               sector: "Agrochemicals" },
  { ticker: "BRITANNIA",   name: "Britannia Industries",                      sector: "FMCG" },
  { ticker: "SHREECEM",    name: "Shree Cement",                              sector: "Cement" },
  { ticker: "PIDILITIND",  name: "Pidilite Industries",                       sector: "Chemicals & Paints" },
  // IT / Technology
  { ticker: "LTIM",        name: "LTIMindtree",                               sector: "Information Technology" },
  { ticker: "MPHASIS",     name: "Mphasis",                                   sector: "Information Technology" },
  { ticker: "PERSISTENT",  name: "Persistent Systems",                        sector: "Information Technology" },
  { ticker: "COFORGE",     name: "Coforge",                                   sector: "Information Technology" },
  { ticker: "TATAELXSI",   name: "Tata Elxsi",                                sector: "Information Technology" },
  { ticker: "KPITTECH",    name: "KPIT Technologies",                         sector: "Information Technology" },
  { ticker: "ZENSARTECH",  name: "Zensar Technologies",                       sector: "Information Technology" },
  { ticker: "MASTEK",      name: "Mastek",                                    sector: "Information Technology" },
  { ticker: "TANLA",       name: "Tanla Platforms",                           sector: "Information Technology" },
  { ticker: "RATEGAIN",    name: "RateGain Travel Technologies",              sector: "Information Technology" },
  { ticker: "NAUKRI",      name: "Info Edge (Naukri)",                        sector: "Information Technology" },
  { ticker: "JUSTDIAL",    name: "Just Dial",                                 sector: "Information Technology" },
  { ticker: "IRCTC",       name: "Indian Railway Catering & Tourism",         sector: "Infrastructure" },
  // Banking & Finance
  { ticker: "BANKBARODA",  name: "Bank of Baroda",                            sector: "Banking & Finance" },
  { ticker: "CANARABANK",  name: "Canara Bank",                               sector: "Banking & Finance" },
  { ticker: "PNB",         name: "Punjab National Bank",                      sector: "Banking & Finance" },
  { ticker: "UNIONBANK",   name: "Union Bank of India",                       sector: "Banking & Finance" },
  { ticker: "INDIANB",     name: "Indian Bank",                               sector: "Banking & Finance" },
  { ticker: "FEDERALBANK", name: "Federal Bank",                              sector: "Banking & Finance" },
  { ticker: "IDFCFIRSTB",  name: "IDFC First Bank",                           sector: "Banking & Finance" },
  { ticker: "AUBANK",      name: "AU Small Finance Bank",                     sector: "Banking & Finance" },
  { ticker: "BANDHANBNK",  name: "Bandhan Bank",                              sector: "Banking & Finance" },
  { ticker: "RBLBANK",     name: "RBL Bank",                                  sector: "Banking & Finance" },
  { ticker: "YESBANK",     name: "Yes Bank",                                  sector: "Banking & Finance" },
  { ticker: "LICHSGFIN",   name: "LIC Housing Finance",                       sector: "Banking & Finance" },
  { ticker: "CHOLAFIN",    name: "Cholamandalam Investment",                  sector: "Banking & Finance" },
  { ticker: "M&MFIN",      name: "Mahindra & Mahindra Financial Services",    sector: "Banking & Finance" },
  { ticker: "MANAPPURAM",  name: "Manappuram Finance",                        sector: "Banking & Finance" },
  { ticker: "MUTHOOTFIN",  name: "Muthoot Finance",                           sector: "Banking & Finance" },
  { ticker: "PIRAMALENT",  name: "Piramal Enterprises",                       sector: "Banking & Finance" },
  { ticker: "JIOFIN",      name: "Jio Financial Services",                    sector: "Banking & Finance" },
  { ticker: "HDFCAMC",     name: "HDFC AMC",                                  sector: "Banking & Finance" },
  { ticker: "NIPPONLIFE",  name: "Nippon India AMC",                          sector: "Banking & Finance" },
  { ticker: "ICICIGI",     name: "ICICI Lombard General Insurance",           sector: "Insurance" },
  { ticker: "ICICIPRULI",  name: "ICICI Prudential Life Insurance",           sector: "Insurance" },
  { ticker: "STARHEALTH",  name: "Star Health Insurance",                     sector: "Insurance" },
  { ticker: "GICRE",       name: "General Insurance Corporation",             sector: "Insurance" },
  { ticker: "NIACL",       name: "New India Assurance",                       sector: "Insurance" },
  // Pharma & Healthcare
  { ticker: "LUPIN",       name: "Lupin",                                     sector: "Pharmaceuticals" },
  { ticker: "TORNTPHARM",  name: "Torrent Pharmaceuticals",                   sector: "Pharmaceuticals" },
  { ticker: "BIOCON",      name: "Biocon",                                    sector: "Pharmaceuticals" },
  { ticker: "GLENMARK",    name: "Glenmark Pharmaceuticals",                  sector: "Pharmaceuticals" },
  { ticker: "IPCALAB",     name: "IPCA Laboratories",                         sector: "Pharmaceuticals" },
  { ticker: "AUROPHARMA",  name: "Aurobindo Pharma",                          sector: "Pharmaceuticals" },
  { ticker: "GRANULES",    name: "Granules India",                            sector: "Pharmaceuticals" },
  { ticker: "LAURUSLABS",  name: "Laurus Labs",                               sector: "Pharmaceuticals" },
  { ticker: "ALKEM",       name: "Alkem Laboratories",                        sector: "Pharmaceuticals" },
  { ticker: "ABBOTINDIA",  name: "Abbott India",                              sector: "Pharmaceuticals" },
  { ticker: "PFIZER",      name: "Pfizer India",                              sector: "Pharmaceuticals" },
  { ticker: "GLAXO",       name: "GSK Pharmaceuticals",                       sector: "Pharmaceuticals" },
  { ticker: "FORTIS",      name: "Fortis Healthcare",                         sector: "Healthcare" },
  { ticker: "MAXHEALTH",   name: "Max Healthcare",                            sector: "Healthcare" },
  { ticker: "NARAYANA",    name: "Narayana Hrudayalaya",                      sector: "Healthcare" },
  { ticker: "RAINBOW",     name: "Rainbow Children's Medicare",               sector: "Healthcare" },
  // FMCG & Consumer
  { ticker: "DABUR",       name: "Dabur India",                               sector: "FMCG" },
  { ticker: "MARICO",      name: "Marico",                                    sector: "FMCG" },
  { ticker: "GODREJCP",    name: "Godrej Consumer Products",                  sector: "FMCG" },
  { ticker: "COLPAL",      name: "Colgate-Palmolive India",                   sector: "FMCG" },
  { ticker: "EMAMILTD",    name: "Emami",                                     sector: "FMCG" },
  { ticker: "PGHH",        name: "Procter & Gamble Hygiene & Health",         sector: "FMCG" },
  { ticker: "VBL",         name: "Varun Beverages",                           sector: "FMCG" },
  { ticker: "RADICO",      name: "Radico Khaitan",                            sector: "FMCG" },
  { ticker: "UNITDSPR",    name: "United Spirits",                            sector: "FMCG" },
  { ticker: "JUBLFOOD",    name: "Jubilant FoodWorks",                        sector: "Consumer Goods" },
  { ticker: "DEVYANI",     name: "Devyani International",                     sector: "Consumer Goods" },
  { ticker: "SAPPHIRE",    name: "Sapphire Foods India",                      sector: "Consumer Goods" },
  { ticker: "RELAXO",      name: "Relaxo Footwears",                          sector: "Consumer Goods" },
  { ticker: "BATA",        name: "Bata India",                                sector: "Consumer Goods" },
  { ticker: "METROBRAND",  name: "Metro Brands",                              sector: "Consumer Goods" },
  { ticker: "CAMPUS",      name: "Campus Activewear",                         sector: "Consumer Goods" },
  { ticker: "PAGEIND",     name: "Page Industries",                           sector: "Consumer Goods" },
  // Automobiles
  { ticker: "BAJAJ-AUTO",  name: "Bajaj Auto",                                sector: "Automobile" },
  { ticker: "TVSMOTOR",    name: "TVS Motor Company",                         sector: "Automobile" },
  { ticker: "ASHOKLEY",    name: "Ashok Leyland",                             sector: "Automobile" },
  { ticker: "MOTHERSON",   name: "Samvardhana Motherson",                     sector: "Automobile" },
  { ticker: "BOSCH",       name: "Bosch India",                               sector: "Automobile" },
  { ticker: "APOLLOTYRE",  name: "Apollo Tyres",                              sector: "Automobile" },
  { ticker: "CEATLTD",     name: "CEAT",                                      sector: "Automobile" },
  { ticker: "BALKRISIND",  name: "Balkrishna Industries",                     sector: "Automobile" },
  { ticker: "SCHAEFFLER",  name: "Schaeffler India",                          sector: "Automobile" },
  { ticker: "TIINDIA",     name: "Tube Investments of India",                 sector: "Automobile" },
  // Energy & Power
  { ticker: "TATAPOWER",   name: "Tata Power",                                sector: "Power & Energy" },
  { ticker: "TORNTPOWER",  name: "Torrent Power",                             sector: "Power & Energy" },
  { ticker: "JSWENERGY",   name: "JSW Energy",                                sector: "Power & Energy" },
  { ticker: "CESC",        name: "CESC",                                      sector: "Power & Energy" },
  { ticker: "ADANIGREEN",  name: "Adani Green Energy",                        sector: "Power & Energy" },
  { ticker: "ADANIPOWER",  name: "Adani Power",                               sector: "Power & Energy" },
  { ticker: "NHPC",        name: "NHPC",                                      sector: "Power & Energy" },
  { ticker: "SJVN",        name: "SJVN",                                      sector: "Power & Energy" },
  { ticker: "PFC",         name: "Power Finance Corporation",                 sector: "Banking & Finance" },
  { ticker: "RECLTD",      name: "REC Limited",                               sector: "Banking & Finance" },
  // Infrastructure & Real Estate
  { ticker: "DLF",         name: "DLF",                                       sector: "Real Estate" },
  { ticker: "GODREJPROP",  name: "Godrej Properties",                         sector: "Real Estate" },
  { ticker: "OBEROIRLTY",  name: "Oberoi Realty",                             sector: "Real Estate" },
  { ticker: "PRESTIGE",    name: "Prestige Estates Projects",                 sector: "Real Estate" },
  { ticker: "BRIGADE",     name: "Brigade Enterprises",                       sector: "Real Estate" },
  { ticker: "SOBHA",       name: "Sobha",                                     sector: "Real Estate" },
  { ticker: "PHOENIXLTD",  name: "Phoenix Mills",                             sector: "Real Estate" },
  { ticker: "MAHLIFE",     name: "Mahindra Lifespace Developers",             sector: "Real Estate" },
  { ticker: "IRFC",        name: "Indian Railway Finance Corporation",        sector: "Infrastructure" },
  { ticker: "RVNL",        name: "Rail Vikas Nigam",                          sector: "Infrastructure" },
  { ticker: "HUDCO",       name: "Housing & Urban Dev. Corp.",                sector: "Infrastructure" },
  { ticker: "IRB",         name: "IRB Infrastructure",                        sector: "Infrastructure" },
  { ticker: "GMR",         name: "GMR Airports Infrastructure",               sector: "Infrastructure" },
  { ticker: "CONCOR",      name: "Container Corporation of India",            sector: "Infrastructure" },
  { ticker: "APLAPOLLO",   name: "APL Apollo Tubes",                          sector: "Metals & Steel" },
  // Metals & Mining
  { ticker: "VEDL",        name: "Vedanta",                                   sector: "Metals & Steel" },
  { ticker: "NMDC",        name: "NMDC",                                      sector: "Mining" },
  { ticker: "NATIONALUM",  name: "National Aluminium Company",                sector: "Metals & Steel" },
  { ticker: "JINDALSTEL",  name: "Jindal Steel & Power",                      sector: "Metals & Steel" },
  { ticker: "JSL",         name: "Jindal Stainless",                          sector: "Metals & Steel" },
  { ticker: "MOIL",        name: "MOIL",                                      sector: "Mining" },
  { ticker: "RATNAMANI",   name: "Ratnamani Metals & Tubes",                  sector: "Metals & Steel" },
  // Cement
  { ticker: "JKCEMENT",    name: "JK Cement",                                 sector: "Cement" },
  { ticker: "RAMCOCEM",    name: "Ramco Cements",                             sector: "Cement" },
  { ticker: "INDIACEM",    name: "India Cements",                             sector: "Cement" },
  { ticker: "HEIDELBERG",  name: "HeidelbergCement India",                    sector: "Cement" },
  { ticker: "DALMIACEM",   name: "Dalmia Bharat",                             sector: "Cement" },
  { ticker: "JKLAKMISHMI", name: "JK Lakshmi Cement",                         sector: "Cement" },
  // Chemicals
  { ticker: "SRF",         name: "SRF",                                       sector: "Chemicals" },
  { ticker: "DEEPAKNTR",   name: "Deepak Nitrite",                            sector: "Chemicals" },
  { ticker: "AARTIIND",    name: "Aarti Industries",                          sector: "Chemicals" },
  { ticker: "NOCIL",       name: "NOCIL",                                     sector: "Chemicals" },
  { ticker: "VINATIORGA",  name: "Vinati Organics",                           sector: "Chemicals" },
  { ticker: "FINEORG",     name: "Fine Organic Industries",                   sector: "Chemicals" },
  { ticker: "TATACHEM",    name: "Tata Chemicals",                            sector: "Chemicals" },
  { ticker: "GNFC",        name: "Gujarat Narmada Valley Fertilizers",        sector: "Chemicals" },
  { ticker: "CHAMBLFERT",  name: "Chambal Fertilizers",                       sector: "Agrochemicals" },
  { ticker: "COROMANDEL",  name: "Coromandel International",                  sector: "Agrochemicals" },
  // Telecom, Media & Aviation
  { ticker: "IDEA",        name: "Vodafone Idea",                             sector: "Telecom" },
  { ticker: "INDIGO",      name: "InterGlobe Aviation (IndiGo)",              sector: "Aviation" },
  { ticker: "SUNTV",       name: "Sun TV Network",                            sector: "Media" },
  { ticker: "ZEEL",        name: "Zee Entertainment",                         sector: "Media" },
  { ticker: "NETWORK18",   name: "Network18 Media",                           sector: "Media" },
  // Consumer Tech & Fintech
  { ticker: "ZOMATO",      name: "Zomato",                                    sector: "Consumer Tech" },
  { ticker: "NYKAA",       name: "FSN E-Commerce (Nykaa)",                    sector: "Consumer Tech" },
  { ticker: "PAYTM",       name: "One 97 Communications (Paytm)",             sector: "Fintech" },
  { ticker: "POLICYBZR",   name: "PB Fintech (PolicyBazaar)",                 sector: "Fintech" },
  { ticker: "CARTRADE",    name: "CarTrade Tech",                             sector: "Consumer Tech" },
  { ticker: "DELHIVERY",   name: "Delhivery",                                 sector: "Logistics" },
  { ticker: "INFIBEAM",    name: "Infibeam Avenues",                          sector: "Fintech" },
  // Electronics & Consumer Goods
  { ticker: "HAVELLS",     name: "Havells India",                             sector: "Consumer Goods" },
  { ticker: "VOLTAS",      name: "Voltas",                                    sector: "Consumer Goods" },
  { ticker: "BLUESTARCO",  name: "Blue Star",                                 sector: "Consumer Goods" },
  { ticker: "WHIRLPOOL",   name: "Whirlpool of India",                        sector: "Consumer Goods" },
  { ticker: "CROMPTON",    name: "Crompton Greaves Consumer",                 sector: "Consumer Goods" },
  { ticker: "DIXON",       name: "Dixon Technologies",                        sector: "Electronics" },
  { ticker: "AMBER",       name: "Amber Enterprises India",                   sector: "Electronics" },
  { ticker: "KAYNES",      name: "Kaynes Technology India",                   sector: "Electronics" },
  { ticker: "SYRMA",       name: "Syrma SGS Technology",                      sector: "Electronics" },
  // Others
  { ticker: "RAYMOND",     name: "Raymond",                                   sector: "Textiles" },
  { ticker: "TRIDENT",     name: "Trident",                                   sector: "Textiles" },
  { ticker: "WELCORP",     name: "Welspun Corp",                              sector: "Metals & Steel" },
  { ticker: "MAPMYINDIA",  name: "CE Info Systems (MapMyIndia)",              sector: "Information Technology" },
  { ticker: "ROUTE",       name: "Route Mobile",                              sector: "Information Technology" },
  { ticker: "HAPPSTMNDS",  name: "Happiest Minds Technologies",               sector: "Information Technology" },
  { ticker: "NEWGEN",      name: "Newgen Software",                           sector: "Information Technology" },
  { ticker: "TATACOMM",    name: "Tata Communications",                       sector: "Information Technology" },
  { ticker: "GODREJIND",   name: "Godrej Industries",                         sector: "Conglomerate" },
]

export const BSE_STOCKS: StockInfo[] = [
  { ticker: "TATAINVEST",  name: "Tata Investment Corporation",               sector: "Banking & Finance" },
  { ticker: "CENTURYTEX",  name: "Century Textiles & Industries",             sector: "Textiles" },
  { ticker: "CENTURYPLY",  name: "Century Plyboards",                         sector: "Consumer Goods" },
  { ticker: "WELSPUNIND",  name: "Welspun India",                             sector: "Textiles" },
  { ticker: "JYOTHYLAB",   name: "Jyothy Labs",                               sector: "FMCG" },
  { ticker: "PCBL",        name: "PCBL (Philips Carbon Black)",               sector: "Chemicals" },
  { ticker: "REDINGTON",   name: "Redington India",                           sector: "Information Technology" },
  { ticker: "SPANDANA",    name: "Spandana Sphoorty Financial",               sector: "Banking & Finance" },
  { ticker: "FIVESTAR",    name: "Five-Star Business Finance",                sector: "Banking & Finance" },
  { ticker: "TCNSBRANDS",  name: "TCNS Clothing",                             sector: "Consumer Goods" },
]

export const ALL_STOCKS: StockInfo[] = [...NSE_STOCKS, ...BSE_STOCKS]
